{{- if .Values.ingress.enabled -}}
{{- $fullName := include "fullname" . -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "static.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
    - hosts:
        - jencub.xyz
      secretName: {{ .Values.secretName }}
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /{{ .Values.hostpath | default "" }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
    {{- if .Values.ingress.hosts }}
    {{ range $i, $host := .Values.ingress.hosts }}
    - host: {{ $host.name }}
      http:
        paths:
          - path: /{{ $host.path | default "" }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
    {{- end }}
    {{- end }}
{{- end }}
